server:
  port: 80
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/fv_music?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: #
      driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    database: 1
    port: 6379
    timeout: 3000ms